<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>PRAGMATA_AP</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.1">
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AssemblyGenerator">
      <HintPath>lib\AssemblyGenerator.dll</HintPath>
    </Reference>
    <Reference Include="Hexa.NET.ImGui">
      <HintPath>lib\Hexa.NET.ImGui.dll</HintPath>
    </Reference>
    <Reference Include="HexaGen.Runtime">
      <HintPath>lib\HexaGen.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>lib\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp">
      <HintPath>lib\Microsoft.CodeAnalysis.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="REFCoreDeps">
      <HintPath>lib\REFCoreDeps.dll</HintPath>
    </Reference>
    <Reference Include="REFramework.NET">
      <HintPath>lib\REFramework.NET.dll</HintPath>
    </Reference>
    <Reference Include="application">
      <HintPath>lib\REFramework.NET.application.dll</HintPath>
    </Reference>
    <Reference Include="viacore">
      <HintPath>lib\REFramework.NET.viacore.dll</HintPath>
    </Reference>
    <Reference Include="_System.Private.CoreLib">
      <HintPath>lib\REFramework.NET._System.Private.CoreLib.dll</HintPath>
    </Reference>
  </ItemGroup>

	<PropertyGroup>
		<BuildDir>$(ProjectDir)bin\$(Platform)\$(Configuration)\$(TargetFramework)</BuildDir>
		<REframeworkPath>D:\Steam\steamapps\common\PRAGMATA\reframework\plugins\managed</REframeworkPath>
		<APPackage>Archipelago.MultiClient.Net.dll</APPackage>
		<Newtonsoft>Newtonsoft.Json.dll</Newtonsoft>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	  <IsPublishable>False</IsPublishable>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
	  <IsPublishable>False</IsPublishable>
	</PropertyGroup>

	<ItemGroup>
		<PluginFiles Include="$(BuildDir)\$(AssemblyName).dll" />
		<DebugFiles Include="$(BuildDir)\$(AssemblyName).pdb" />
		<DependencyFiles Include="$(BuildDir)\$(APPackage); $(BuildDir)\$(Newtonsoft)" />
	</ItemGroup>

	<Target Name="CopyToPublish" AfterTargets="Build">
		<Copy SourceFiles="@(PluginFiles)" DestinationFiles="$(PublishDir)$(AssemblyName).dll" />
		<Copy SourceFiles="@(DependencyFiles)" DestinationFiles="$(PublishDir)dependencies\$(APPackage); $(PublishDir)dependencies\$(Newtonsoft)" />
		<Copy Condition="$(Configuration) == 'Debug'" SourceFiles="@(DebugFiles)" DestinationFiles="$(PublishDir)$(AssemblyName).pdb" />
	</Target>

	<Target Name="CopyToGame" AfterTargets="Build" DependsOnTargets="CopyToPublish">
		<Copy SourceFiles="@(PluginFiles)" DestinationFiles="$(REframeworkPath)\$(AssemblyName).dll" />
		<Copy SourceFiles="@(DependencyFiles)" DestinationFiles="$(REframeworkPath)\dependencies\$(APPackage); $(REframeworkPath)\dependencies\$(Newtonsoft)" ContinueOnError="true" Retries="0" />
		<Copy Condition="$(Configuration) == 'Debug'" SourceFiles="@(DebugFiles)" DestinationFiles="$(REframeworkPath)\$(AssemblyName).pdb" />
	</Target>

</Project>
